name : "onnx_model"
backend: "onnxruntime"
max_batch_size : 8
instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]
dynamic_batching {
  max_queue_delay_microseconds: 100
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 160, 45 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "logit"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
