name: AWS-BeanStalk-Pipeline

env:
  APP_NAME : Deeplolaimodelproduct
  ENV_NAME : Deeplolaimodelproduct-env-1
  AWS_REGION_NAME : ap-northeast-2
  DEPLOY_PKG_NAME : ai_model_serving_app.zip

on:
  push:
    branches:
      - master

jobs:
  deeploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make zip pkg
        run: zip -r ${{ env.DEPLOY_PKG_NAME }} . -x "*.git*"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: ${{ env.ENV_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION_NAME }}
          deployment_package: ${{ env.DEPLOY_PKG_NAME }}